receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed   # thay logging
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp/jaeger:
    endpoint: "jaeger:4317"   # Jaeger OTLP gRPC port
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/jaeger]

    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
