# This is a generated file. Not intended for manual editing.
services:
  practice01.startup:
    build:
      context: "C:\\Users\\ninhn\\RiderProjects\\Practice01"
      dockerfile: "src/Practice01.Startup/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "practice01startup:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57400"
    volumes:
    - "C:\\Users\\ninhn\\RiderProjects\\Practice01\\src\\Practice01.Startup:/app:rw"
    - "C:\\Users\\ninhn\\RiderProjects\\Practice01:/src:rw"
    - "C:\\Users\\ninhn\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\ninhn\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.6\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\ninhn\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\ninhn\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_8_26_21_16_23:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
